from .rol import Rol
from .plan import Plan
from .usuario import Usuario
from .profesor import Profesor
from .estudiante import Estudiante
from .curso import Curso
from .inscripcion import Inscripcion
from .tema import Tema
from .tarea import Tarea
from .entrega import Entrega
from .logro import Logro
from .estudiante_logro import EstudianteLogro
from .pago import Pago